# This workflow will run a build and publish a package to npm when a
# release is published.

name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build 
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_TOKEN}}
